### ISSUE TITLE
Issue with example

### ISSUE THREAD

**Issue by nitin25191** [sudheerj/ECMAScript-features#2]
var even = number => {
    if(number % 2) {
        console.log("Even");
    } else {
        console.log("Odd");
    }
}
even(5);

Hi please rectify this example, the console will print opposite results for the numbers i.e. for 2, it will result odd while for 5 it's returning even.

**Comment by sudheerj** [comment]
@nitin25191  Thanks for pointing out. I just need to remove the spaces
