### ISSUE TITLE
Class example is not appropriate

### ISSUE THREAD

**Issue by archersunx** [sudheerj/ECMAScript-features#25]
This Class example has a problem，setting area would case infinite loop。I know it's just an example，but it may confuse someone new to the language

```
class Square {
  constructor(length) {
    this.length = length;
  }

  get area() {
    return this.length * this.length;
  }

  set area(value) {
    this.area = value;
  }
}
````

**Comment by sudheerj** [comment]
@archersunx  Thanks for notifying this bug. Fixed it.
